import "./globals.css";

import { Providers } from "@/app/providers/provider";

export const metadata = {
  title: "Rick and Morty Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
